// <auto-generated />
namespace CandidateManagement.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class security : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(security));
        
        string IMigrationMetadata.Id
        {
            get { return "201701101528515_security"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
